name: WorldEater
version: '${project.version}'
main: org.worldeater.worldeater.WorldEater
api-version: 1.19
depend: [ ProtocolLib ]
commands:
  eatworld:
    description: Eat this world
    usage: /eatworld <join|leave|create|stop>
#permissions:
#  operator:
#    default: true
#    description: Operator